var vm=new Vue({
    el:"#graph1",
    data:{
        newNfc:{
            num:"2",
            place:"20180611",
            tag:"陈某",
            statu:"多处破损",
            xy:"(12,54)",
            describe:"(12,54)",  
        },
        storage:[{
            num:"2",
            place:"20180611",
            tag:"陈某",
            statu:"多处破损",
            xy:"(12,54)",
            describe:"看起来还行应该没坏",  
        },{
            num:"2",
            place:"20180611",
            tag:"陈某",
            statu:"多处破损",
            xy:"(12,54)",
            describe:"看起来还行应该没坏",  
        },{
            num:"2",
            place:"20180611",
            tag:"陈某",
            statu:"多处破损",
            xy:"(12,54)",
            describe:"看起来还行应该没坏",  
        },{
            num:"2",
            place:"20180611",
            tag:"陈某",
            statu:"多处破损",
            xy:"(12,54)",
            describe:"看起来还行应该没坏",  
        },{
            num:"2",
            place:"20180611",
            tag:"陈某",
            statu:"多处破损",
            xy:"(12,54)",
            describe:"看起来还行应该没坏",  
        },{
            num:"2",
            place:"20180611",
            tag:"陈某",
            statu:"多处破损",
            xy:"(12,54)",
            describe:"看起来还行应该没坏",  
        },{
            num:"2",
            place:"20180611",
            tag:"陈某",
            statu:"多处破损",
            xy:"(12,54)",
            describe:"看起来还行应该没坏",  
        }
        ]
    },//end data
   
    
})
